name: Advanced Development Build

on:
  push:
    branches: [ develop ]

jobs:
  build:
    uses: bbapp-grp/workflow-template/.github/workflows/development-build.yml@main
    with:
      service_name: "CHANGE_ME"  # Update this to your microservice name
      gcp_project_id: "bbapp-dev-440805"
      dockerfile_path: "docker/Dockerfile"  # Custom Dockerfile location
      build_context: "."
      node_version: "18"  # Specific Node.js version
      enable_tests: true
      test_command: "npm run test:ci"  # Custom test command
      build_command: "npm run build"  # Pre-Docker build step
      artifact_registry_region: "us-west1"  # Different region
      artifact_registry_repo: "my-custom-repo"  # Custom repository
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }}
