# Go Development Workflow with Testing
name: Development Build

on:
  push:
    branches: [ develop ]

jobs:
  test:
    name: Run Tests
    uses: bbapp-grp/workflow-template/.github/workflows/golang-test.yml@main
    with:
      go_version: '1.21'
      test_command: 'go test ./...'
      lint_command: 'golangci-lint run'
      vet_command: 'go vet ./...'
      enable_lint: true
      enable_vet: true
      enable_race_detection: true

  build:
    name: Build and Push
    needs: test
    if: success()
    
    uses: bbapp-grp/workflow-template/.github/workflows/development-build.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      WIF_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
