# Node.js Release Workflow with Testing
name: Release Build

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    uses: bbapp-grp/workflow-template/.github/workflows/nodejs-test.yml@main
    with:
      node_version: '20'
      test_command: 'npm test'
      lint_command: 'npm run lint'
      type_check_command: 'npm run type-check'
      enable_lint: true
      enable_type_check: true

  build:
    name: Build and Push
    needs: test
    if: success()
    
    uses: bbapp-grp/workflow-template/.github/workflows/release-build.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      WIF_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  update-manifests:
    name: Update K8s Manifests
    needs: build
    if: success()
    
    uses: bbapp-grp/workflow-template/.github/workflows/gitops-update.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      image_digest: ${{ needs.build.outputs.image_digest }}
      k8s_repo: 'bbapp-grp/k8s'
      k8s_repo_branch: 'main'
      kustomize_path: 'overlays/prod'
      create_pr: true  # Create PR for production environment
    secrets:
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}
