name: Release Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: bbapp-grp/workflow-template/.github/workflows/release-build.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      enable_tests: false  # Python tests typically handled in Dockerfile
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }}
