name: Kaniko Container Build and Push

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of the microservice (defaults to repository name)'
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      dockerfile_path:
        description: 'Path to Dockerfile relative to repo root'
        required: false
        type: string
        default: 'Dockerfile'
      build_context:
        description: 'Build context directory'
        required: false
        type: string
        default: '.'
      gcp_project_id:
        description: 'GCP Project ID'
        required: true
        type: string
      artifact_registry_region:
        description: 'Artifact Registry region'
        required: false
        type: string
        default: 'us-central1'
      artifact_registry_repo:
        description: 'Artifact Registry repository name'
        required: false
        type: string
        default: 'bbapp-microservices'
      image_tag_suffix:
        description: 'Additional tag suffix for development builds'
        required: false
        type: string
        default: 'latest'
    secrets:
      WIF_PROVIDER:
        description: 'Workload Identity Federation Provider'
        required: true
      WIF_SERVICE_ACCOUNT:
        description: 'Workload Identity Federation Service Account'
        required: true
    outputs:
      image_tag:
        description: 'The full image tag that was built and pushed'
        value: ${{ jobs.build.outputs.image_tag }}

env:
  REGISTRY: ${{ inputs.artifact_registry_region }}-docker.pkg.dev
  IMAGE_NAME: ${{ inputs.gcp_project_id }}/${{ inputs.artifact_registry_repo }}/${{ inputs.service_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag_suffix }}
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Build and push with Kaniko
        uses: aevea/action-kaniko@master
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ inputs.image_tag_suffix }}
          path: ${{ inputs.build_context }}
          build_file: ${{ inputs.dockerfile_path }}
          cache: true
          cache_registry: ${{ env.REGISTRY }}/${{ inputs.gcp_project_id }}/cache

      - name: Output image details
        run: |
          echo "Image built and pushed: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag_suffix }}"
